s7/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("s7uploads.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

s7uploads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from . import views

app_name = "s7uploads"

urlpatterns = [
    re_path(r"^$", views.IndexView.as_view(), name="index"),
    path("<int:page>/", views.IndexView.as_view(), name="index"),
    path("search_uploads/", views.search_uploads, name="search_uploads"),
    path("<int:page>/search_uploads/", views.search_uploads, name="search_uploads"),
    path("search_uploads/<str:params>", views.search_uploads, name="search_uploads"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("uploads/<int:pk>/", views.UploadView.as_view(), name="upload"),
    path("edit/<int:pk>/", views.EditUploadView.as_view(), name="edit"),
    path("newversion/<int:pk>/", views.NewVersionView.as_view(), name="newversion"),
    path("delete/<int:pk>/", views.delete_upload, name="delete"),
    path("delete_review/<int:pk>/", views.delete_review, name="delete_review"),
    path("delete_ss/<int:pk>/", views.delete_screenshot, name="delete_ss"),
    path("new_upload/", views.upload_file, name="new_upload"),
    path("uploads/<int:pk>/add_review", views.add_review, name="add_review"),
    path("reviews/", views.ReviewView.as_view(), name="reviews"),
    path("users/", views.UserListView.as_view(), name="users"),
    path("about/", views.about_view, name="about"),
    path("community/", views.community_view, name="community"),
    path("download/<int:pk>", views.download_file, name="download"),
]

s7uploads/models.py
import datetime
from django.db.models import Count, Sum, Avg
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.db import models
from django.db.models.signals import post_save
from django.core.validators import MinValueValidator, MaxValueValidator
from django.dispatch import receiver
from django.utils.text import slugify


class S7User(models.Model):
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)

    def num_uploads(self):
        return Upload.objects.filter(user=self).count()

    def num_reviews(self):
        return Review.objects.filter(user=self).count()

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def update_user(sender, instance, created, **kwargs):
    if created:
        S7User.objects.create(user=instance)


class Upload(models.Model):
    user = models.ForeignKey(S7User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.TextField(verbose_name="Upload Description")
    total_downloads = models.IntegerField()

    def indexScreenshot(self):
        return Screenshot.objects.filter(upload=self)[0].url

    def avg_review(self):
        reviews = Review.objects.filter(upload=self)
        num_reviews = reviews.count()
        if num_reviews == 0:
            return 0
        else:
            return reviews.aggregate(Sum("rating"))["rating__sum"] / reviews.count()

    def num_reviews(self):
        return review_set.count()

    def __str__(self):
        return self.title


class File(models.Model):
    url = models.CharField(max_length=100)


class UploadVersion(models.Model):
    upload_id = models.ForeignKey(Upload, on_delete=models.CASCADE)
    file_id = models.ForeignKey(File, on_delete=models.CASCADE)
    date_added = models.DateTimeField()
    version_notes = models.TextField()
    version_name = models.CharField(max_length=10)
    num_downloads = models.IntegerField()
    avg_rating = models.DecimalField(decimal_places=2, max_digits=10)

    def total_stars(self):
        reviews = Review.objects.filter(upload=self)
        num_reviews = reviews.count()
        if num_reviews == 0:
            return 0
        else:
            return reviews.aggregate(Sum("rating"))["rating__sum"]

    def update_ranking(self):
        reviews = Review.objects.filter(upload=self)
        self.avg_rating = reviews.aggregate(Avg("rating"))["rating__avg"]
        self.save()


class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    uploads = models.ManyToManyField(Upload, related_name="tags")

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Tag, self).save(*args, **kwargs)


class Screenshot(models.Model):
    url = models.CharField(max_length=100)
    upload = models.ForeignKey(Upload, on_delete=models.CASCADE)

    def __str__(self):
        return self.url


class Review(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField(max_length=2048, verbose_name="Review Text")
    upload = models.ForeignKey(UploadVersion, on_delete=models.CASCADE)
    user = models.ForeignKey(S7User, on_delete=models.CASCADE)
    pubDate = models.DateTimeField("date published")
    rating = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )

    def __str__(self):
        return self.user.user.username + self.upload.title

s7uploads/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Review, Upload


class SignUpForm(UserCreationForm):
    email = forms.EmailField(help_text="*")

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("title", "text", "rating")

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields["title"].widget.attrs.update(
            {"placeholder": "Review Title...", "onfocus": "this.placeholder=''"}
        )
        self.fields["text"].widget.attrs.update(
            {"placeholder": "Review this upload...", "onfocus": "this.placeholder=''"}
        )


class SearchForm(forms.Form):
    search_line = forms.CharField(max_length=200, required=False)

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields["search_line"].widget.attrs.update(
            {"placeholder": "  Search infini7y...", "onfocus": "this.placeholder=''"}
        )


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    description = forms.CharField()
    versionNotes = forms.CharField(required=False)
    versionNumber = forms.CharField(max_length=5)
    file = forms.FileField()
    screenshots = forms.FileField(
        widget=forms.ClearableFileInput(attrs={"multiple": True}), required=False
    )
    tagline = forms.CharField(required=False)


class EditUploadForm(forms.Form):
    title = forms.CharField(max_length=50)
    description = forms.CharField()
    versionNotes = forms.CharField(required=False)
    versionNumber = forms.CharField(max_length=5)
    tagline = forms.CharField(required=False)


class NewVersionForm(forms.Form):
    description = forms.CharField()
    versionNotes = forms.CharField(required=True)
    versionNumber = forms.CharField(max_length=5, required=True)
    tagline = forms.CharField(required=False)
    file = forms.FileField()


class AddScreenshotForm(forms.Form):
    screenshots = forms.FileField(
        widget=forms.ClearableFileInput(attrs={"multiple": True})
    )

s7uploads/views.py
import math

from django.db.models import Count, Q, Sum
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from django.utils import timezone
from django.urls import path
from django.views import generic

import operator

from .models import *
from .forms import *

from .authorization import authorize_file_upload
from .filehandler import *


def about_view(request):
    return render(request, "s7uploads/about.html")


def community_view(request):
    if request.method == "POST":
        return render(request, "s7uploads/community.html")
    else:
        searchform = SearchForm()
        return render(request, "s7uploads/community.html", {"search_form": searchform})


def search_uploads(request, params="", page=0):
    if request.method == "POST":
        form = SearchForm(request.POST)

        if form.is_valid():
            search_tags = form.cleaned_data.get("search_line")
            sort_by = request.POST["searchorder"]
            filter_by = request.POST["searchcategory"]

            tag_line = "tags=" + search_tags
            sort_line = "sort=" + sort_by
            filter_line = "filter=" + filter_by

            get_line = "?" + "&".join([tag_line, sort_line, filter_line])
            url = "/s7uploads/" + get_line
            return HttpResponseRedirect(url)

    else:
        form = SearchForm()
        url = "/s7uploads/" + params
        return HttpResponseRedirect(url)


def add_review(request, pk):
    if not request.user.is_anonymous:
        if request.method == "POST":
            form = ReviewForm(request.POST)

            if form.is_valid():
                review = form.save(commit=False)
                review.pubDate = timezone.now()
                review.upload = UploadVersion.objects.get(pk=pk)
                review.user = S7User.objects.get(user=request.user)
                review.save()
                review.upload.update_ranking()

                url = "/s7uploads/uploads/" + str(pk)
                return HttpResponseRedirect(url)

        else:
            form = ReviewForm()
            searchform = SearchForm(request.POST)
            return render(
                request,
                "s7uploads/upload.html",
                {
                    "upload": UploadVersion.objects.get(pk=pk),
                    "form": form,
                    "search_form": searchform,
                },
            )
    else:
        return redirect("s7uploads:signup")


def delete_upload(request, pk):
    user = request.user
    upload = UploadVersion.objects.get(pk=pk)

    if (
        not user.is_anonymous
        and upload is not None
        and upload.upload_id.user.user.id == user.id
    ):
        upload.delete()
    else:
        print("Unauthorized attempt to delete upload.")

    return redirect("s7uploads:index")


def delete_screenshot(request, pk):
    user = request.user
    ss = Screenshot.objects.get(pk=pk)

    if not user.is_anonymous and ss is not None and ss.upload.user.user.id == user.id:
        ss.delete()
    else:
        print("Unauthorized attempt to delete upload.")

    # TODO: redirect to previously viewed upload
    return redirect("s7uploads:index")


def delete_review(request, pk):
    user = request.user
    review = Review.objects.get(pk=pk)
    upload_id = review.upload.id

    if not user.is_anonymous and review is not None and review.user.user.id == user.id:
        review.delete()
    else:
        print("Unauthorized attempt to delete review")

    # TODO: just refresh instead?
    return redirect("s7uploads:upload", upload_id)


def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("s7uploads:index")
        else:
            form = AuthenticationForm()
            return render(
                request, "s7uploads/login.html", {"form": form, "invalid": True}
            )
    else:
        form = AuthenticationForm()

    return render(request, "s7uploads/login.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("s7uploads:index")


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("s7uploads:index")
    else:
        form = SignUpForm()

    return render(request, "s7uploads/signup.html", {"form": form})


def download_file(request, pk):
    version = UploadVersion.objects.get(pk=pk)
    upload = version.upload_id
    upload.total_downloads += 1
    version.num_downloads += 1
    version.save(update_fields=["num_downloads"])
    upload.save(update_fields=["total_downloads"])
    return handle_download_file(version.file_id.url)


def upload_file(request):

    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)

        if (
            form.is_valid()
            and authorize_file_upload(request)
            and valid_upload_ext(request.FILES["file"].name)
        ):
            # upload file
            upload = handle_uploaded_file(form, request.FILES["file"], request.user)

            # upload screenshots
            for s in request.FILES.getlist("screenshots"):
                if valid_screenshot_ext(s.name):
                    handle_uploaded_screenshot(form, s, upload)
                else:
                    # TODO: Let user know the extension was valid
                    print("Invalid image extension.")

            return redirect("s7uploads:index")
        # TODO: else tell the user to log in
    else:
        form = UploadFileForm()

    return render(request, "s7uploads/newupload.html", {"form": form})


class IndexView(generic.ListView):
    model = UploadVersion
    template_name = "s7uploads/index.html"
    context_object_name = "latest_upload_list"
    total_num_uploads = 0
    uploads_per_page = 7

    # select option -> filter param
    order_dict = {
        "newest": "-date_added",
        "oldest": "date_added",
        "bestrated": "-avg_rating",
        "mostrated": "-num_reviews",
        "mostdownloads": "-upload_id__total_downloads",
    }

    def get_uploads_in_range(self, uploads):
        # the -1 is due to displaying start page as 1 instead of 0 in browser
        start_page = self.kwargs["page"] - 1 if "page" in self.kwargs else 0
        start_index = start_page * self.uploads_per_page
        end_index = start_index + self.uploads_per_page
        return uploads[start_index:end_index]

    def get_queryset(self):
        get = self.request.GET

        uploads = Upload.objects.none()
        tagged_uploads = Upload.objects.none()
        named_uploads = Upload.objects.none()
        tagged_versions = UploadVersion.objects.none()
        named_versions = UploadVersion.objects.none()

        # default ordering if no order is supplied
        order_by = IndexView.order_dict["newest"]

        if len(get) == 0:
            uploads = UploadVersion.objects.filter(date_added__lte=timezone.now())
        else:
            order_by = get.get("sort")
            filter_by = get.get("filter")
            search_tag = get.get("tags")

            if order_by in IndexView.order_dict:
                order_by = IndexView.order_dict[order_by]

            if filter_by != None and filter_by in (
                "maps",
                "scenarios",
                "plugins",
                "scripts",
                "utilities",
                "physics",
            ):
                try:
                    tag_obj = Tag.objects.get(slug=filter_by)
                except:
                    all_uploads = Upload.objects.none()
            else:
                all_uploads = Upload.objects.all()

            if len(search_tag) > 0:
                tags = [tag.strip() for tag in search_tag.split()]

                for tag in tags:
                    # get uploads with matching tags
                    try:
                        tag_obj = Tag.objects.get(slug=tag)
                        if tag_obj:
                            tagged_uploads = tagged_uploads | all_uploads.filter(
                                tags=tag_obj
                            )
                    except:
                        continue

                tagged_versions = UploadVersion.objects.filter(
                    upload_id__in=tagged_uploads
                )

                # get uploads with matching name
                for tag in tags:
                    if len(tag) >= 3:
                        named_uploads = named_uploads | all_uploads.filter(
                            title__contains=tag
                        )

                named_versions = UploadVersion.objects.filter(
                    upload_id__in=named_uploads
                )

                uploads = (tagged_versions | named_versions).distinct()
            else:
                uploads = UploadVersion.objects.filter(upload_id__in=all_uploads)

        self.total_num_uploads = len(uploads)

        return self.get_uploads_in_range(
            uploads.annotate(num_reviews=Count("review")).order_by(order_by)
        )

    def get_page_list(self):
        num_pages = math.ceil(self.total_num_uploads / self.uploads_per_page)
        page_list = ""

s7uploads/templates/s7uploads/editupload.html
{% extends "s7uploads/navbar.html" %}

{% load static %}
{% load upload_tags %}

{% block content %}

<section id="main-content">

{% if user %}
	<section id="userbanner">
		{% if user.is_anonymous %}
			<h4>You are not logged in!</h4>
		{% else %}
			<img src="/static/s7uploads/images/default_profile.jpg"></img>
			<section id="userbannertext">
				<h3><a href="{% url 's7uploads:index' %}?tags={{user.username}}">{{ user.username }}</a></h3>
			<h5>{{ s7user.num_uploads }} uploads</h5>
			<h5>{{ s7user.num_reviews }} reviews</h5>
			<section id="sideupload">
			<a href="{%url 's7uploads:new_upload' %}">+ Upload</a>
			</section>
			</section>
		{% endif %}
	</section>
{% endif %}

<section id="singleupload">
{% if user.is_authenticated %}
<section id="upload">
	<section id="uploadheader">
		<form enctype="multipart/form-data" method="post">
			{% csrf_token %}

		<a id="delete" href="{% url 's7uploads:upload' pk=upload.id %}">Cancel</a>
		<h1>{{form.title}} by {{ upload.upload_id.user.user.username }}</h1>

		<div id="blackstripe"></div>

		<section id="uploadtext">
			<h3>{{ upload.upload_id.user.user.username }} on {{ upload.date_added }} </h3>
			{{ form.description.as_textarea }}
			<br>
			<br>
			<h4> Version {{ form.versionNumber }} Notes: </h4>
			<br>
			<p> {{ form.versionNotes.as_textarea }} </p>

			<h4> Tags </h4>
			{{ form.tagline }}
			<br>
			<br>
			<input type="submit" name='submit-edit' value="Submit Changes">
			</form>
			<br><br>
		</section>


		<section id="thumbnailscreenshots">
			{% for screenshot in upload.upload_id.screenshot_set.all %}
				<section id="thumbnailscreenshot">
                    <img src="{% get_media_prefix %}{{screenshot.url}}" alt="{{screenshot.url}}"></img>
				<a id="deletess" href="{% url 's7uploads:delete_ss' pk=screenshot.id %}">⛝</a>
				</section>
			{% endfor %}
			<form enctype="multipart/form-data" method="post">
			{% csrf_token %}
			<br>{{screenshotform.screenshots}}<br><br>
			<input type="submit" name='submit-ss' value="+ Add Screenshot">
			</form>
		</section>


	</section>
</section>
{% endif %}

</section>


</section>
{% endblock %}

s7uploads/templates/s7uploads/index.html
{% extends "s7uploads/navbar.html" %}

{% load static %}
{% load url_tags %}
{% load upload_tags %}

{% block content %}

<section id="main-content">
{% if user %}
	{% if user.is_anonymous %}
		<section id="userbanner-nolog">
			<h4>You are not logged in!</h4>
		</section>
	{% else %}
		<section id="userbanner">
			<img src="/static/s7uploads/images/default_profile.jpg"></img>
			<section id="userbannertext">
			<h3><a href="{% url 's7uploads:index' %}?tags={{user.username}}">{{ user.username }}</a></h3>
			<h5>{{ s7user.num_uploads }} uploads</h5>
			<h5>{{ s7user.num_reviews }} reviews</h5>
			<section id="sideupload">
			<a href="{%url 's7uploads:new_upload' %}">⇡ Upload</a>
			</section>
			</section>
		</section>
	{% endif %}
{% endif %}

<section id="upload">
<span class="whitetitle"><h1> Latest Updates and Submissions </h1></span>


{% if latest_upload_list %}

	<ul>
	{% for upload in latest_upload_list %}
		{% with upload.upload_id as u %}

		<li>
		<section id="indexheader">
		<span class="mediumtext">
		<section id="indexuploadtext">
			<h2><span class="plainlink"><a href="{%url 's7uploads:upload' upload.id %}">{{ u.title }} {{ upload.version_name }}</a></span> by <span class="bluelink"><a href="linktouser">{{ u.user.user.username }}</a></span></h2>
			<a id="download" href="{%url 's7uploads:download' upload.id %}">⇣ Download</a>
			{% if user|user_owns_upload:upload.user %}
			<a id="download" href="{%url 's7uploads:edit' upload.id %}">Edit</a>
			{% endif %}

		</section>
		</section>

		{% if upload.upload_id.screenshot_set.exists %}
		<section id="imgcrop">
            		<img src="{% get_media_prefix %}{{upload.upload_id.indexScreenshot}}" alt="{% get_media_prefix %}{{upload.upload_id.indexScreenshot}}" id="middle"></img>
		</section>
		{% endif %}
		</span>
		

		<section id="indexuploadtext">
			<p><b>Description: </b>{{ u.description|truncatewords:20 }}</p>
			<br>
			<p> <b>Version {{upload.version_name}} Notes: </b>{{ upload.version_notes|truncatewords:10 }} </p>
			<br>
			<h3>Posted on {{ upload.date_added }} </h3>
		</section>
		<section id="indexuploadtext">
			{% if upload.upload_id.tags %}
			<span class="blue">
			<p>
				{% for tag in upload.upload_id.tags.all %}
				#{{tag.name}}
				{% endfor %}
				<br><br>
			</p>
			</span>
			{% endif %}
			<p>
			{{u.total_downloads}} downloads, {{upload.avg_rating}} average rating
			</p>
		</section>
		</li>
			{% endwith %}
	{% endfor %}
	</ul>

{% else %}

	<p> Nothing to see here. </p>

{% endif %}

	<section id="pagenums">
	{% for page in num_pages %}
		<a href="{% url 's7uploads:index' page %}?{{request.GET.urlencode}}">{{page}}</a>
	{% endfor %}
	</section>

</section>

</section>
{% endblock %}

s7uploads/templates/s7uploads/navbar.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 's7uploads/style.css' %}">

{% block content %}

{% endblock %}

{% block navbar %}
<div id = "banner">
	<nav>
	<ul id="navlinks">
		<li><a href="{%url 's7uploads:index' %}" class="lightlink">infini<span class="sitecolor">7</span>y</a></li>
		<li ><a href="{%url 's7uploads:index' %}" class="lightlink">Downloads</a></li>
		<li><a href="{%url 's7uploads:reviews' %}" class="lightlink">Reviews</a></li>
		<li><a href="{%url 's7uploads:users' %}" class="lightlink">Users</a></li>
		<li><a href="https://github.com/vakkiri/infini7y" class="lightlink" >Github</a></li>
		<li><a href="{%url 's7uploads:community' %}" class="lightlink" >Community</a></li>
		{% if user.is_anonymous %}
			<li><a href="{%url 's7uploads:signup' %}" class="boldlink">Sign Up</a></li>
			<li><a href="{%url 's7uploads:login' %}" class="boldlink">Log In</a></li>
		{% else %}
			<li><a href="{%url 's7uploads:logout' %}" class="boldlink">Log Out</a></li>
		{% endif %}
	<ul/>
	</nav>
</div>
<div id="searchbanner">
	<section id="searchbannercontent">
		<form action="search_uploads/?{{ request.GET.urlencode }}" method="post">
			<button class="searchicon" action="submit">☌</button>
			{% csrf_token %}
			{% for field in search_form %}
			{{ field }}
			{% endfor %}

			<select name="searchcategory" id="searchcategory" class="searchcategory">
			<option value="any" selected>All Files</option>
			<option value="maps">Maps</option>
			<option value="scenarios">Scenarios</option>
			<option value="plugins">Plugins</option>
			<option value="scripts">Scripts</option>
			<option value="utilities">Utilities</option>
			<option value="physics">Physics</option>
		</select>
		<select name="searchorder" id="searchorder" class="searchcategory">
			<option value="newest" selected>Newest</option>
			<option value="oldest">Oldest</option>
			<option value="bestrated">Best Rated</option>
			<option value="mostrated">Most Rated</option>
			<option value="mostdownloads">Most Downloads</option>
		</select>


		</form>
	</section>
</div>

<div id="stripe"></div>
{% endblock %}

s7uploads/templates/s7uploads/upload.html
{% extends "s7uploads/navbar.html" %}

{% load static %}
{% load upload_tags %}

{% block content %}

<section id="main-content">

{% if user %}
		{% if user.is_anonymous %}
		<section id="userbanner-nolog">
			<h4>You are not logged in!</h4>
		</section>
		{% else %}
		<section id="userbanner">
			<img src="/static/s7uploads/images/default_profile.jpg"></img>
			<section id="userbannertext">
				<h3><a href="{% url 's7uploads:index' %}?tags={{user.username}}">{{ user.username }}</a></h3>
			<h5>{{ s7user.num_uploads }} uploads</h5>
			<h5>{{ s7user.num_reviews }} reviews</h5>
			<section id="sideupload">
			<a href="{%url 's7uploads:new_upload' %}">+ Upload</a>
			</section>
			</section>
		</section>
		{% endif %}
{% endif %}

<section id="singleupload">
	<section id="uploadheader">
		<a id="download" href="#">Download</a>
		{% if user|user_owns_upload:upload.upload_id.user %}
		<a id="editupload" href="{% url 's7uploads:newversion' upload.id %}">New Version</a>
		<a id="editupload" href="{% url 's7uploads:edit' upload.id %}">Edit</a>
		<a id="delete" href="{% url 's7uploads:delete' pk=upload.id %}">Delete</a>
		{% endif %}
		<div id="upload-title">
			<h1>{{ upload.upload_id.title }}</h1><h3> by </h3><h2>{{ upload.upload_id.user.user.username }}</h2>
		</div>

		<div id="blackstripe"></div>
	</section>

	<section id="thumbnailscreenshots">
		{% for screenshot in upload.upload_id.screenshot_set.all %}
			<section id="thumbnailscreenshot">
			    <img src="{% get_media_prefix %}{{screenshot.url}}" alt="{{screenshot.url}}"></img>
			</section>
		{% endfor %}
	</section>

	<section id="uploadtext">
		<p>{{ upload.upload_id.description|linebreaks }}</p>
		<br>
		<h4> Version {{upload.version_name}} Notes: </h4>
		<br>
		<p> {{ upload.version_notes|linebreaks }} </p>
		<br>

		<h3>Updated {{ upload.date_added }} </h3>
		<br>

		<h4> Upload Statistics: </h4><br>
		<p>
		downloads: {{upload.num_downloads}} <br>
		stars: {{upload.total_stars}} <br>
		</p>
		<br>
		<p>
		{% for tag in upload.upload_id.tags.all %}
		#{{tag.name}} 
		{% endfor %}
		</p>
	</section>


	<section id="review">
		<div id="blackstripe"></div>
			{% if form %}
				<br>
				<form action="add_review" method="post">
					{% csrf_token %}
					{{ form.title }}
					{{ form.text }}
					{{ form.rating }}
					<br><br>
					<span id="submitbutton">
					<input type="submit" value="Add Review">
					</span>
					<br>
				</form>
			{% else %}
				{% if not user|user_owns_upload:upload.upload_id.user and not user.is_anonymous %}
				<a href="{%url 's7uploads:add_review' pk=upload.pk%}" id="addreview" >+ Add Review</a>
				{% endif %}
			<br>
			<br>
			{% endif %}

		{% if upload.review_set.exists %}
			<h1>Reviews</h1>
			<div id="blackstripe"></div>

			<ul>
			{% for review in upload.review_set.all %}
				<li>
				{% if user|user_owns_review:review and not user.is_anonymous %}
					<a id="delete" href="{% url 's7uploads:delete_review' pk=review.id %}">Delete</a>
				{% endif %}
				<h2 class="review">{{review.title}}</h2>
				<h3 id="review-rating">{{review.rating}}/5</h3>
				<h3>By {{review.user.user.username}} on {{review.pubDate}}</h3>
				<p>{{review.text|linebreaks}}</p>
				</li>
			{% endfor %}
			</ul>
		{% else %}
			<br>
			<h1>No reviews yet!</h1>
				<br>
		{% endif %}
	</section>


</section>

</section>

{% endblock %}